---

- include: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: jf.openresty | main | create nginx group
  group: name=nginx gid=9001

- name: jf.openresty | main | template main config
  template: src=nginx.conf.j2 dest=/usr/local/openresty/nginx/conf/nginx.conf
  notify:
    - reload nginx

- name: jf.openresty | main | ensure nginx is running
  service: name=openresty state=started enabled=yes
